# Generated by Django 4.1.6 on 2023-02-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_email',
            new_name='email',
        ),
    ]
